### ISSUE TITLE
About the rendered results in the paper.

### ISSUE THREAD

**Issue by duzhenjiang113** [LordLiang/GA-Sketching#1]
Thanks for your excellent work!!! Could you please tell me the method for rendering the mesh results in the paper?

**Comment by LordLiang** [comment]
> Thanks for your excellent work!!! Could you please tell me the method for rendering the mesh results in the paper?

Sure! I used this wonderful tool. It is very easy to use!
https://github.com/HTDerekLiu/BlenderToolbox
(*^ω^*)
