### ISSUE TITLE
problem about running the UI interface

### ISSUE THREAD

**Issue by Lanjiong-Li** [LordLiang/GA-Sketching#2]
I find that in [edit_widget.py](https://github.com/LordLiang/GA-Sketching/blob/main/GA-Sketching-UI/sketch_3d_ui/edit_widget.py), there are some functions about shadow, and I also check the paper ShadowDraw. My problem is, is the Data Generation step necessary? Is it for building a shadow dataset to guide the users? Can you provide thoes images or I have to build it myself?
Many thanks!

**Comment by LordLiang** [comment]
It is not necessary. 
1. You can ignore related codes about shadow. Without it, it may be a little difficult to draw the correct sketch consistent with the viewpoint.
2. You can randomly select some samples from the dataset to generate the shadow, as I do. I generate the dataset via the scripts under [tools/sketch_rendering/](https://github.com/LordLiang/GA-Sketching/tree/main/tools/sketch_rendering). Here I have provided same samples in [sketch_transparent_20.zip](https://github.com/LordLiang/GA-Sketching/tree/main/sketch_transparent_20.zip).
3. You can use some fixed samples to generate the shadow.

**Comment by Lanjiong-Li** [comment]
Thanks for your reply, it works now and hope that I can make some contributions based on your method.
