### ISSUE TITLE
mesh_type and pytorch3d version

### ISSUE THREAD

**Issue by staymylove** [LordLiang/GA-Sketching#4]
Dear author:
   I want to ask the pytorch3d version if I use pip(ERROR: Could not find a version that satisfies the requirement pytorch3d==2.31 (from versions: 0.1.1, 0.2.0, 0.2.5, 0.3.0)); 
   And I want to use my own mesh data, should I use the the 'mesh-fusion' to change my mesh to 'xxx.off' ? The normal '.obj' mesh can not work?
   I am looking forward to your reply!

**Comment by staymylove** [comment]
And I try the conda install 
But I got the error:
/data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/scipy/__init__.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.19.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/data/zeju/GA-Sketching/tools/sketch_rendering/gen_dn_from_mesh.py", line 4, in <module>
    from pytorch3d.renderer.cameras import (
  File "/data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: /data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationERKSs

**Comment by LordLiang** [comment]
> Dear author: I want to ask the pytorch3d version if I use pip(ERROR: Could not find a version that satisfies the requirement pytorch3d==2.31 (from versions: 0.1.1, 0.2.0, 0.2.5, 0.3.0)); And I want to use my own mesh data, should I use the the 'mesh-fusion' to change my mesh to 'xxx.off' ? The normal '.obj' mesh can not work? I am looking forward to your reply!

It is OK if your mesh is watertight (which is needed for boundary sampling). The file type does not matter.

**Comment by LordLiang** [comment]
> And I try the conda install But I got the error: /data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/scipy/**init**.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.19.2) warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}" Traceback (most recent call last): File "/data/zeju/GA-Sketching/tools/sketch_rendering/gen_dn_from_mesh.py", line 4, in from pytorch3d.renderer.cameras import ( File "/data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/pytorch3d/renderer/**init**.py", line 3, in from .blending import ( File "/data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in from pytorch3d import _C ImportError: /data/zeju/anaconda3/envs/fantasia/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationERKSs

some version information:
python 3.9.15
pytorch3d 0.7.4
scipy 1.11.2
numpy 1.23.0

**Comment by staymylove** [comment]
Thanks for your patient answer and reply. I have solved the version and mesh problems by your instructions.
