### ISSUE TITLE
render 2d for comparison to generated sketch.

### ISSUE THREAD

**Issue by staymylove** [LordLiang/GA-Sketching#5]
Dear author：
  After I generated the sketches by your script, I want to compare to 2d color-img rendered by 3D mesh.  Do you have the script to get the rendered 2d img? I would greatly appreciate it.

**Comment by LordLiang** [comment]
I think you can refer to the official tutorials of Pytorch3d for [rendering RGB images from textured meshes](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_textured_meshes.ipynb).

**Comment by staymylove** [comment]
Thank you for your reply. I will try it.
